builds:
  - binary: "xfab"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    env:
      - CGO_ENABLED=0
    flags: 
      - -mod=vendor

# archives:
#   - id: linux_archive
#     builds:
#       - linux_build
#     format: tar.gz
#     name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#     # files:
#     #   - docs/**
#     #   - README.md
#     #   - ./backend/config/*

#   - id: windows_archive
#     builds:
#       - windows_build
#     format: zip
#     name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  prerelease: auto

checksum:
  name_template: "checksums.txt"
    algorithm: sha256
