name: Impact Simulation

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

permissions:
  contents: read  #doing it explicitly

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: Impact Simulation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.10.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}


      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "586989009432"


      - name: Get access token
        id: token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-identity-token)
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: POST to Cloud Run
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"your":"payload"}'
