name: "Impact Simulation"
 
on:
 pull_request:
   branches:
   - main
   paths:
   - terraform/**
 
env:
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
 terraform:
   name: "Impact Simulation"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
    
     - name: Generate Terraform Plan
       run: |
         terraform init
         terraform validate
         terraform plan -out=tfplan.binary
         terraform show -json tfplan.binary | grep -v "^::" | grep -v "^\[" | grep -v "^2025" | grep -v "^::debug" > tfplan.json
         PLAN_CONTENT=$(cat tfplan.json | tr -d '\n' | base64 -w 0)
         echo "PLAN_CONTENT<<EOF" >> $GITHUB_ENV
         echo "$PLAN_CONTENT" >> $GITHUB_ENV
         echo "EOF" >> $GITHUB_ENV

     - name: Send Plan and Wait for Analysis
       id: send-plan
       uses: fjogeleit/http-request-action@v1
       with:
         url: ${{ secrets.WEBHOOK_URL }}
         method: POST
         contentType: 'application/json'
         data: '{"plan": "${{ env.PLAN_CONTENT }}"}'
         timeout: 600000  # 10 minutes in milliseconds
         retry: 3
         retryWait: 5000
         responseFile: 'analysis.md'  # Save response to file
         preventFailureOnNoResponse: true

     - name: Print Response Details
       run: |
         echo "Response Status Code: ${{ steps.send-plan.outputs.statusCode }}"
         echo "Response Body:"
         cat analysis.md

     - name: Post Analysis as PR Comment
       uses: actions/github-script@v6
       with:
         script: |
            const fs = require('fs');
            const analysis = fs.readFileSync('analysis.md', 'utf8');
            const prNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: prNumber,
              body: analysis
            });
 